set(CMAKE_SYSROOT "C:/MinGW-Kit/w32/mingw32/")

set(CMAKE_SYSTEM_PREFIX_PATH "C:/MinGW-Kit/w32/mingw32/")

set(CMAKE_C_COMPILER "C:/MinGW-Kit/w32/mingw32/bin/gcc.exe")
set(CMAKE_CXX_COMPILER "C:/MinGW-Kit/w32/mingw32/bin/g++.exe")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)
